# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pollen < Formula
  desc "Mesh network daemon"
  homepage ""
  version "0.1.0-alpha.17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.17/pollen_0.1.0-alpha.17_darwin_amd64.tar.gz"
      sha256 "2a3ccf6f6eff550a57e4b29e48731b158f2ac1ee2263b9d179f0bb6e221e0e3a"

      define_method(:install) do
        bin.install "pollen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.17/pollen_0.1.0-alpha.17_darwin_arm64.tar.gz"
      sha256 "05631a6d05624636fcdaa2d806a5211b12b57d048227c88769c70eeab9e9545f"

      define_method(:install) do
        bin.install "pollen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.17/pollen_0.1.0-alpha.17_linux_amd64.tar.gz"
      sha256 "916af1f5a5f39520e692e4109c5929f79e63a92df34abf8db93a16deeec680de"
      define_method(:install) do
        bin.install "pollen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.17/pollen_0.1.0-alpha.17_linux_arm64.tar.gz"
      sha256 "e6e061ee477f596d8150000c88781f7e807d9e9871dcc536347b2c677cca55c6"
      define_method(:install) do
        bin.install "pollen"
      end
    end
  end

  service do
    run [opt_bin/"pollen", "up"]
    keep_alive true
    log_path var/"log/pollen.log"
    error_log_path var/"log/pollen.log"
  end
end
