# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pollen < Formula
  desc "Mesh network daemon"
  homepage ""
  version "0.1.0-alpha.16"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.16/pollen_0.1.0-alpha.16_darwin_amd64.tar.gz"
      sha256 "ddf62be05968eaa6f1bd21875b644ab7d665685a4de993a905d6c806de00a567"

      define_method(:install) do
        bin.install "pollen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.16/pollen_0.1.0-alpha.16_darwin_arm64.tar.gz"
      sha256 "b5045d797867b81a0e0481ddac8cf4b0b231cc80a9f7a6d507da5fa2a1210aa8"

      define_method(:install) do
        bin.install "pollen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.16/pollen_0.1.0-alpha.16_linux_amd64.tar.gz"
      sha256 "afc01a76331e40e4535c2477f091e4508b24df36cca2e2254339f3a4b21f1552"
      define_method(:install) do
        bin.install "pollen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.16/pollen_0.1.0-alpha.16_linux_arm64.tar.gz"
      sha256 "bf18c82e4a6e4cbc8b6da640fc9551b6d3e458b31db5273a8900280c4ec1364c"
      define_method(:install) do
        bin.install "pollen"
      end
    end
  end

  service do
    run [opt_bin/"pollen", "up"]
    keep_alive true
    log_path var/"log/pollen.log"
    error_log_path var/"log/pollen.log"
  end
end
